const fs = require('fs');

const NEW_TESTS = [
  {
    slug: "mpsc-polity-constitution",
    title: "MPSC Prelims — Indian Polity & Maharashtra Governance",
    description: "20 high-yield MCQs on the Indian Constitution, 73rd/74th Constitutional Amendments, High Court, Governor, and Maharashtra Panchayati Raj.",
    examType: "MPSC",
    topic: "Polity",
    difficulty: "Medium",
    durationMinutes: 20,
    totalQuestions: 20,
    marksPerQuestion: 2,
    negativeMark: 0.5,
    youtubeQuery: "MPSC polity indian constitution preparation strategy",
    questions: [
      { id: 1, text: "Which Article of the Constitution deals with the appointment of the Governor of a State?", options: { A: "Article 153", B: "Article 155", C: "Article 161", D: "Article 167" }, correct: "B", explanation: "Under Article 155, the Governor of a State is appointed by the President by warrant under his hand and seal." },
      { id: 2, text: "The 73rd Constitutional Amendment Act, 1992 added which Schedule to the Constitution of India?", options: { A: "10th Schedule", B: "11th Schedule", C: "12th Schedule", D: "9th Schedule" }, correct: "B", explanation: "The 73rd Amendment added the 11th Schedule containing 29 functional items for Panchayati Raj Institutions." },
      { id: 3, text: "Who acts as the Secretary of the Gram Panchayat in Maharashtra?", options: { A: "Sarpanch", B: "Gram Sevak", C: "Block Development Officer (BDO)", D: "Talathi" }, correct: "B", explanation: "The Gram Sevak acts as the ex-officio Secretary of the Gram Panchayat, maintains its records, and implements rural schemes." },
      { id: 4, text: "Under which Article can the High Court of Bombay issue Writs for enforcement of Fundamental Rights?", options: { A: "Article 32", B: "Article 226", C: "Article 227", D: "Article 136" }, correct: "B", explanation: "Article 226 empowers High Courts to issue directions, orders or writs (including Habeas Corpus, Mandamus, Prohibition, Quo Warranto, and Certiorari)." },
      { id: 5, text: "In Maharashtra, what is the minimum age required to contest the Gram Panchayat election?", options: { A: "18 years", B: "21 years", C: "25 years", D: "30 years" }, correct: "B", explanation: "Under Article 243F and Maharashtra Village Panchayats Act, the minimum age to contest elections to local bodies is 21 years." },
      { id: 6, text: "Which Committee recommended the three-tier Panchayati Raj system in Maharashtra?", options: { A: "Balwant Rai Mehta Committee", B: "Vasantrao Naik Committee", C: "Ashok Mehta Committee", D: "L.M. Singhvi Committee" }, correct: "B", explanation: "The Vasantrao Naik Committee (1960) recommended the administrative structure for Maharashtra's 3-tier Panchayati Raj system, making Zilla Parishad the key tier." },
      { id: 7, text: "The Right to Information Act came into force across India in which year?", options: { A: "2002", B: "2004", C: "2005", D: "2008" }, correct: "C", explanation: "The RTI Act was passed on 15 June 2005 and came fully into force on 12 October 2005." },
      { id: 8, text: "How many members are nominated by the Governor to the Maharashtra Legislative Council (Vidhan Parishad)?", options: { A: "1/6th of total members", B: "1/12th of total members", C: "1/3rd of total members", D: "12 members fixed" }, correct: "A", explanation: "Under Article 171(3)(e), 1/6th of the members are nominated by the Governor having special knowledge in literature, science, art, cooperative movement, or social service." },
      { id: 9, text: "Which Article guarantees Equality before Law and Equal Protection of the Laws?", options: { A: "Article 14", B: "Article 15", C: "Article 16", D: "Article 19" }, correct: "A", explanation: "Article 14 states: 'The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.'" },
      { id: 10, text: "The Maharashtra Public Service Commission (MPSC) derives its constitutional mandate from:", options: { A: "Article 312", B: "Article 315", C: "Article 324", D: "Article 280" }, correct: "B", explanation: "Article 315 of the Constitution provides for a Public Service Commission for the Union and a State Public Service Commission for each State." },
      { id: 11, text: "Who was the Chairman of the Drafting Committee of the Indian Constitution?", options: { A: "Dr. Rajendra Prasad", B: "Dr. B.R. Ambedkar", C: "Jawaharlal Nehru", D: "B.N. Rau" }, correct: "B", explanation: "Dr. B.R. Ambedkar was the Chairman of the 7-member Drafting Committee appointed on 29 August 1947." },
      { id: 12, text: "The concept of 'Directive Principles of State Policy' (DPSP) was borrowed from which country?", options: { A: "USA", B: "United Kingdom", C: "Ireland", D: "Canada" }, correct: "C", explanation: "DPSPs contained in Part IV (Articles 36-51) of the Indian Constitution were borrowed from the Constitution of Ireland (1937)." },
      { id: 13, text: "What percentage of seats are reserved for women in Maharashtra local self-government bodies?", options: { A: "33%", B: "50%", C: "25%", D: "30%" }, correct: "B", explanation: "Maharashtra was among the pioneering states to increase women's reservation in Panchayats and Urban Local Bodies to 50% in April 2011." },
      { id: 14, text: "Which Fundamental Right cannot be suspended even during a National Emergency (Article 352)?", options: { A: "Articles 14 and 19", B: "Articles 20 and 21", C: "Articles 21 and 22", D: "Articles 19 and 20" }, correct: "B", explanation: "By the 44th Constitutional Amendment (1978), the right to protection in respect of conviction for offences (Article 20) and right to life & personal liberty (Article 21) cannot be suspended." },
      { id: 15, text: "The quorum required to constitute a sitting of either House of the Maharashtra State Legislature is:", options: { A: "One-tenth of total members or 10 members (whichever is greater)", B: "One-sixth of total members", C: "One-fifth of total members", D: "25 members" }, correct: "A", explanation: "Under Article 189(3), the quorum is ten members or one-tenth of the total number of members of the House, whichever is greater." },
      { id: 16, text: "In which year did the Maharashtra Public Services Guarantee Act come into effect?", options: { A: "2011", B: "2014", C: "2015", D: "2018" }, correct: "C", explanation: "The Maharashtra Right to Public Services Act (RTS Act) was enacted in 2015 to ensure transparent, speedy, and time-bound delivery of government services." },
      { id: 17, text: "Who presides over the joint sitting of the two Houses of Parliament?", options: { A: "President of India", B: "Vice President (Chairman of Rajya Sabha)", C: "Speaker of Lok Sabha", D: "Prime Minister" }, correct: "C", explanation: "Under Article 118(4), a joint sitting of Parliament is presided over by the Speaker of the Lok Sabha (or Deputy Speaker in his absence)." },
      { id: 18, text: "Which Constitutional Amendment reduced the voting age from 21 years to 18 years?", options: { A: "42nd Amendment (1976)", B: "44th Amendment (1978)", C: "61st Amendment (1988)", D: "73rd Amendment (1992)" }, correct: "C", explanation: "The 61st Amendment Act, 1988 amended Article 326 to reduce the voting age from 21 to 18 years, effective 28 March 1989." },
      { id: 19, text: "The executive power of the State of Maharashtra is formally vested in:", options: { A: "Chief Minister", B: "Governor", C: "Chief Secretary", D: "State Cabinet" }, correct: "B", explanation: "Under Article 154(1), the executive power of the State is vested in the Governor and is exercised by him directly or through subordinate officers." },
      { id: 20, text: "Which Article of the Constitution provides for the establishment of a Finance Commission every five years?", options: { A: "Article 265", B: "Article 275", C: "Article 280", D: "Article 300A" }, correct: "C", explanation: "Article 280 provides that the President shall constitute a Finance Commission at the expiration of every fifth year to recommend tax devolution." },
    ]
  },

  {
    slug: "maharashtra-police-written-mock",
    title: "Maharashtra Police Bharti — Written Exam Full Mock",
    description: "20 authentic questions on Marathi Grammar, Maharashtra GK & Police administration, Arithmetic, and Logical Reasoning.",
    examType: "Police Bharti",
    topic: "Full Mock",
    difficulty: "Medium",
    durationMinutes: 20,
    totalQuestions: 20,
    marksPerQuestion: 1,
    negativeMark: 0,
    youtubeQuery: "Maharashtra police bharti written exam question paper practice",
    questions: [
      { id: 1, text: "'सूर्य' या शब्दाचा समानार्थी शब्द खालीलपैकी कोणता नाही?", options: { A: "भास्कर", B: "दिनकर", C: "शशांक", D: "मित्र" }, correct: "C", explanation: "'शशांक' म्हणजे चंद्र. भास्कर, दिनकर, भानू, मित्र, आदित्य हे सूर्याचे समानार्थी शब्द आहेत." },
      { id: 2, text: "महाराष्ट्राचे सध्याचे पोलीस महासंचालक (DGP) कार्यालय कोणत्या शहरात स्थित आहे?", options: { A: "पुणे", B: "मुंबई", C: "नागपूर", D: "नाशिक" }, correct: "B", explanation: "महाराष्ट्र पोलीस मुख्यालय (DGP Office) कुलाबा, मुंबई येथे छत्रपती शिवाजी महाराज टर्मिनस/मंत्रालयाच्या जवळ स्थित आहे." },
      { id: 3, text: "एका संख्येचे २५% जर ७५ असतील, तर ती संख्या कोणती?", options: { A: "२५०", B: "३००", C: "२७५", D: "३५०" }, correct: "B", explanation: "संख्या x मानू. x × २५/१०० = ७५ => x = ७५ × ४ = ३००." },
      { id: 4, text: "महाराष्ट्र पोलीस दलाचे ब्रीदवाक्य (Motto) काय आहे?", options: { A: "सत्यमेव जयते", B: "सद्रक्षणाय खलनिग्रहणाय", C: "सेवा आणि निष्ठा", D: "वीरभोग्या वसुंधरा" }, correct: "B", explanation: "'सद्रक्षणाय खलनिग्रहणाय' (सज्जनांचे रक्षण आणि दुर्जनांचा संहार) हे महाराष्ट्र पोलीस दलाचे ब्रीदवाक्य आहे." },
      { id: 5, text: "मराठी भाषेत एकूण किती मुख्य वर्ण मानले जातात?", options: { A: "४८", B: "५०", C: "५२", D: "४६" }, correct: "C", explanation: "शासनाच्या नवीन नियमानुसार 'अं' व 'अः' (स्वरादी) आणि 'ॲ' व 'ऑ' धरून मराठीत एकूण ५२ वर्ण मानले जातात." },
      { id: 6, text: "महाराष्ट्रात गुप्तवार्ता प्रबोधिनी (State Intelligence Academy) कोठे आहे?", options: { A: "मुंबई", B: "पुणे", C: "नाशिक", D: "अमरावती" }, correct: "B", explanation: "महाराष्ट्र गुप्तवार्ता प्रबोधिनी (SIA) पुणे येथे स्थित आहे." },
      { id: 7, text: "जर एका रांगेत सुरेशचा क्रमांक डावीकडून १५ वा आणि उजवीकडून १८ वा असेल, तर रांगेत एकूण किती मुले आहेत?", options: { A: "३३", B: "३२", C: "३१", D: "३०" }, correct: "B", explanation: "एकूण = (डावीकडून क्रमांक + उजवीकडून क्रमांक) - १ = (१५ + १८) - १ = ३३ - १ = ३२." },
      { id: 8, text: "महाराष्ट्र पोलीस अकादमी (MPA) कोठे आहे, जेथे पोलीस उपनिरीक्षकांना प्रशिक्षण दिले जाते?", options: { A: "पुणे", B: "नाशिक", C: "खडकवासला", D: "नागपूर" }, correct: "B", explanation: "महाराष्ट्र पोलीस अकादमी (MPA) नाशिक येथे स्थित आहे. येथे डीवायएसपी आणि पीएसआय अधिकाऱ्यांना प्रशिक्षण दिले जाते." },
      { id: 9, text: "'वाक्यप्रचार ओळखा: 'उंटावरून शेळ्या हाकणे' म्हणजे काय?", options: { A: "शेळ्या पाळणे", B: "बसल्या बसल्या कामात फुकटचे सल्ले देणे", C: "उंटावर बसणे", D: "कष्टाचे काम करणे" }, correct: "B", explanation: "'उंटावरून शेळ्या हाकणे' म्हणजे प्रत्यक्ष काम न करता केवळ निष्क्रिय राहून सूचना किंवा सल्ले देणे." },
      { id: 10, text: "पोलीस पाटलाची नेमणूक कोण करतो?", options: { A: "पोलीस आयुक्त", B: "उपविभागीय अधिकारी (प्रांत अधिकारी / SDO)", C: "तहसीलदार", D: "जिल्हा पोलीस अधीक्षक" }, correct: "B", explanation: "महाराष्ट्र ग्राम पोलीस अधिनियम १९६७ नुसार पोलीस पाटलाची नेमणूक उपविभागीय दंडाधिकारी (SDO / प्रांत अधिकारी) करतात." },
      { id: 11, text: "दोन संख्यांचे गुणोत्तर ३:५ असून त्यांची बेरीज २४० आहे, तर मोठी संख्या कोणती?", options: { A: "९०", B: "१५०", C: "१२०", D: "१६०" }, correct: "B", explanation: "३x + ५x = २४० => ८x = २४० => x = ३०. मोठी संख्या = ५ × ३० = १५०." },
      { id: 12, text: "सायबर गुन्हे रोखण्यासाठी महाराष्ट्र शासनाने कोणता विशेष विभाग सुरू केला आहे?", options: { A: "MahaCyber", B: "CyberRakshak", C: "CrimeCBT", D: "CID Special" }, correct: "A", explanation: "महाराष्ट्र शासनाने सायबर गुन्हे अन्वेषणासाठी 'MahaCyber' (महाराष्ट्र सायबर) हा विशेष नोडल विभाग स्थापन केला आहे." },
      { id: 13, text: "खालील मालिकेत गाळलेली संख्या कोणती? २, ६, १२, २०, ३०, ?", options: { A: "४०", B: "४२", C: "४४", D: "४८" }, correct: "B", explanation: "फरक: +४, +६, +८, +१०, +१२. म्हणून ३० + १२ = ४२." },
      { id: 14, text: "भारताचे नवीन फौजदारी कायदे (भारतीय न्याय संहिता, नागरिक सुरक्षा संहिता) कोणत्या दिनांकापासून लागू झाले?", options: { A: "२६ जानेवारी २०२४", B: "१ जुलै २०२४", C: "१५ ऑगस्ट २०२४", D: "१ जानेवारी २०२५" }, correct: "B", explanation: "BNS, BNSS आणि BSA हे तिन्ही नवीन कायदे १ जुलै २०२४ पासून संपूर्ण भारतात लागू करण्यात आले." },
      { id: 15, text: "'प्रयोग ओळखा: 'रामाने रावणास मारले.'", options: { A: "कर्तरी प्रयोग", B: "कर्मणी प्रयोग", C: "भावे प्रयोग", D: "मिश्र प्रयोग" }, correct: "C", explanation: "येथे कर्त्याला (रामाने) आणि कर्माला (रावणास) प्रत्यय असून क्रियापद तृतीय पुरुषी नपुंसकलिंगी एकवचनी (मारले) आहे, म्हणून हा भावे प्रयोग आहे." },
      { id: 16, text: "SRPF चे पूर्ण रूप काय आहे?", options: { A: "Special Railway Police Force", B: "State Reserve Police Force", C: "Security Reserve Police Force", D: "State Rapid Police Force" }, correct: "B", explanation: "SRPF म्हणजे State Reserve Police Force (राज्य राखीव पोलीस बल). याची स्थापना १९४८ मध्ये झाली." },
      { id: 17, text: "एका वस्तूची छापील किंमत ₹१,००० असून त्यावर २०% सूट दिली, तर विक्री किंमत किती?", options: { A: "₹७००", B: "₹८००", C: "₹८५०", D: "₹७५०" }, correct: "B", explanation: "सूट = १००० चे २०% = ₹२००. विक्री किंमत = १००० - २०० = ₹८००." },
      { id: 18, text: "महाराष्ट्रात नक्षलग्रस्त भागात कारवाई करण्यासाठी पोलिसांचे कोणते विशेष दल कार्यरत आहे?", options: { A: "Force One", B: "C-60 (सी-६०)", C: "Quick Response Team (QRT)", D: "Black Cats" }, correct: "B", explanation: "गडचिरोली व नक्षलग्रस्त भागात नक्षलविरोधी अभियानासाठी १९९० मध्ये 'C-60' (कमांडो-६०) कमांडो पथक स्थापन करण्यात आले." },
      { id: 19, text: "खालीलपैकी कोणती जोडी विसंगत आहे?", options: { A: "मुंबई — गेटवे ऑफ इंडिया", B: "औरंगाबाद — बिबी का मकबरा", C: "पुणे — शनिवार वाडा", D: "नागपूर — अजिंठा लेणी" }, correct: "D", explanation: "अजिंठा लेणी छत्रपती संभाजीनगर (औरंगाबाद) जिल्ह्यात आहेत, नागपूर येथे नाहीत." },
      { id: 20, text: "पोलीस भरती लेखी परीक्षेत १०० गुणांपैकी किमान किती टक्के गुण मिळवणे आवश्यक असते?", options: { A: "३५%", B: "४०%", C: "५०%", D: "६०%" }, correct: "C", explanation: "महाराष्ट्र पोलीस भरती नियमानुसार लेखी परीक्षेत किमान ५०% गुण मिळवणे आवश्यक असते, त्यानंतरच गुणवत्ता यादीत विचार केला जातो." },
    ]
  },

  {
    slug: "maharashtra-talathi-tcs-mock",
    title: "Maharashtra Talathi Bharti — TCS Pattern Mock Test",
    description: "20 questions strictly based on the TCS pattern across Marathi, English, General Knowledge, and Reasoning.",
    examType: "Talathi Bharti",
    topic: "TCS Pattern",
    difficulty: "Medium",
    durationMinutes: 20,
    totalQuestions: 20,
    marksPerQuestion: 2,
    negativeMark: 0,
    youtubeQuery: "Maharashtra talathi bharti TCS pattern mock test question paper",
    questions: [
      { id: 1, text: "Find the antonym of the given word: 'DILIGENT'", options: { A: "Hardworking", B: "Lazy", C: "Careful", D: "Active" }, correct: "B", explanation: "Diligent means showing care and conscientiousness in one's work. Its antonym is Lazy or Indolent." },
      { id: 2, text: "'ययाति' या ज्ञानपीठ पुरस्कारप्राप्त कादंबरीचे लेखक कोण आहेत?", options: { A: "वि. स. खांडेकर", B: "वि. वा. शिरवाडकर", C: "भालचंद्र नेमाडे", D: "गो. नी. दांडेकर" }, correct: "A", explanation: "'ययाति' कादंबरीसाठी विष्णू सखाराम खांडेकर यांना १९७४ मध्ये मराठीतील पहिला ज्ञानपीठ पुरस्कार मिळाला." },
      { id: 3, text: "Select the correctly spelt word:", options: { A: "Accomodation", B: "Accommodation", C: "Acommodation", D: "Accomadation" }, correct: "B", explanation: "The correct spelling is 'Accommodation' (double c and double m)." },
      { id: 4, text: "महाराष्ट्रात माहितीचा अधिकार (RTI) अर्ज केल्यानंतर सर्वसाधारण माहिती किती दिवसांत मिळणे बंधनकारक आहे?", options: { A: "१५ दिवस", B: "३० दिवस", C: "४५ दिवस", D: "६० दिवस" }, correct: "B", explanation: "माहिती अधिकार कायदा २००५ च्या कलम ७(१) नुसार सर्वसाधारण माहिती अर्ज मिळाल्यापासून ३० दिवसांच्या आत देणे बंधनकारक असते (जीविताशी संबंधित असल्यास ४८ तासांत)." },
      { id: 5, text: "In the sentence 'She is good ___ mathematics', choose the correct preposition:", options: { A: "in", B: "at", C: "with", D: "for" }, correct: "B", explanation: "We use the idiom 'good at' when referring to proficiency in a subject or skill (e.g. good at mathematics, good at singing)." },
      { id: 6, text: "'समास ओळखा: 'नीळकंठ'", options: { A: "अव्ययीभाव", B: "तत्पुरुष", C: "बहुव्रीही", D: "द्वंद्व" }, correct: "C", explanation: "नीळ आहे कंठ ज्याचा असा तो (शंकर) — दोन्ही पदे मुख्य नसून तिसऱ्याच पदाचा बोध होतो, म्हणून हा बहुव्रीही समास आहे." },
      { id: 7, text: "Choose the correct passive voice: 'The government built a new bridge.'", options: { A: "A new bridge was built by the government.", B: "A new bridge is built by the government.", C: "A new bridge has been built by the government.", D: "A new bridge had built by the government." }, correct: "A", explanation: "Simple past active (built) changes to was/were + past participle (was built) in the passive." },
      { id: 8, text: "महाराष्ट्रातील महसूल वर्षाची (Revenue Year) सुरुवात कोणत्या तारखेला होते?", options: { A: "१ जानेवारी", B: "१ एप्रिल", C: "१ ऑगस्ट", D: "१ जून" }, correct: "C", explanation: "महाराष्ट्र जमीन महसूल संहितेनुसार महसूल वर्ष १ ऑगस्ट ते ३१ जुलै या कालावधीत गणले जाते." },
      { id: 9, text: "'वाक्यरूपांतर: 'तो वेगाने धावतो.' (नकारार्थी करा)", options: { A: "तो हळू धावत नाही.", B: "तो सावकाश धावत नाही.", C: "तो धावत नाही.", D: "तो वेगात नसतो." }, correct: "B", explanation: "अर्थ न बदलता नकारार्थी करताना 'वेगाने' या शब्दाचा विरुद्धार्थी शब्द 'सावकाश/हळू' वापरून नकार दिला जातो: 'तो सावकाश धावत नाही.'" },
      { id: 10, text: "७/१२ (सातबारा) उताऱ्यामध्ये गाव नमुना '७' काय दर्शवितो?", options: { A: "पिकांची नोंद", B: "मालकी हक्क व भोगवटादार", C: "कर्ज व तगावी", D: "सिंचनाचे साधन" }, correct: "B", explanation: "गाव नमुना ७ हा अधिकार अभिलेख पत्रक असून मालकी हक्क, भूमापन क्रमांक व क्षेत्र दर्शवतो; तर नमुना १२ हा पीक पाहणी पत्रक असतो." },
      { id: 11, text: "Identify the part with error: 'Neither of the two candidates (A) / have submitted (B) / their original documents (C) / No error (D)'", options: { A: "Neither of the two candidates", B: "have submitted", C: "their original documents", D: "No error" }, correct: "B", explanation: "'Neither of' takes a singular verb. It should be 'has submitted', not 'have submitted'." },
      { id: 12, text: "महाराष्ट्रात सर्वांत कमी वने कोणत्या जिल्ह्यात आढळतात?", options: { A: "जालना", B: "लातूर", C: "सोलापूर", D: "बीड" }, correct: "B", explanation: "लातूर जिल्ह्यात वनक्षेत्राचे प्रमाण सर्वांत कमी (१% पेक्षाही कमी) आहे." },
      { id: 13, text: "एक ट्रेन ३६ किमी/तास वेगाने धावत असल्यास तिचा मीटर/सेकंद मध्ये वेग किती?", options: { A: "८ मी/से", B: "१० मी/से", C: "१२ मी/से", D: "१५ मी/से" }, correct: "B", explanation: "किमी/तास वरून मी/से करण्यासाठी ५/१८ ने गुणावे: ३६ × (५/१८) = १० मीटर/सेकंद." },
      { id: 14, text: "तापी नदी कोणत्या समुद्राला जाऊन मिळते?", options: { A: "बंगालचा उपसागर", B: "अरबी समुद्र", C: "हिंदी महासागर", D: "कच्छचे आखात" }, correct: "B", explanation: "तापी ही पश्चिमवाहिनी नदी असून ती सुरतजवळ खंभाताच्या आखातात (अरबी समुद्रात) जाऊन मिळते." },
      { id: 15, text: "Give one word for: 'A person who knows many languages'", options: { A: "Polyglot", B: "Linguist", C: "Philosopher", D: "Grammarian" }, correct: "A", explanation: "A person who knows and speaks many languages is called a 'Polyglot'." },
      { id: 16, text: "'विभक्ती ओळखा: 'घराबाहेर' यातील 'बाहेर' हे कोणत्या प्रकारचे शब्दयोगी अव्यय आहे?", options: { A: "कालवाचक", B: "स्थलवाचक", C: "करणवाचक", D: "तुलनावाचक" }, correct: "B", explanation: "'घराबाहेर' हे ठिकाण दर्शवते, म्हणून ते स्थलवाचक शब्दयोगी अव्यय आहे." },
      { id: 17, text: "एका दुकानदाराने ₹५०० ची वस्तू ₹६०० ला विकली, तर त्याला शेकडा किती नफा झाला?", options: { A: "१५%", B: "२०%", C: "२५%", D: "१८%" }, correct: "B", explanation: "नफा = ६०० - ५०० = १००. शेकडा नफा = (१००/५००) × १०० = २०%." },
      { id: 18, text: "जिल्हाधिकारी यांच्या हाताखाली काम करणारा 'सर्कल ऑफिसर' (मंडळ अधिकारी) किती तलाठी सजांवर देखरेख करतो?", options: { A: "२ ते ३ सजा", B: "५ ते ८ सजा", C: "१० ते १२ सजा", D: "१५ सजा" }, correct: "B", explanation: "मंडळ अधिकारी (Circle Officer) साधारणतः ५ ते ८ तलाठी सजांच्या कामाचे पर्यवेक्षण करतो." },
      { id: 19, text: "Find the odd one out: 64, 125, 216, 343, 512, 729, 1000, 1024", options: { A: "343", B: "512", C: "729", D: "1024" }, correct: "D", explanation: "All numbers are cubes of integers (4³, 5³, 6³, 7³, 8³, 9³, 10³), but 1024 is 2¹⁰ or 32², not a perfect cube." },
      { id: 20, text: "महाराष्ट्र जमीन महसूल अधिनियम कोणत्या वर्षीचा आहे?", options: { A: "१९६०", B: "१९६६", C: "१९७२", D: "१९५६" }, correct: "B", explanation: "महाराष्ट्र जमीन महसूल संहिता (Maharashtra Land Revenue Code - MLRC) ही १९६६ मध्ये मंजूर करण्यात आली." },
    ]
  },

  {
    slug: "rbi-grade-b-economy-finance",
    title: "RBI Grade B — Economic & Social Issues (ESI)",
    description: "20 high-standard questions on Macroeconomics, Inflation indices (CPI/WPI), Monetary Policy, and Union Budget.",
    examType: "Banking",
    topic: "ESI & Finance",
    difficulty: "Hard",
    durationMinutes: 20,
    totalQuestions: 20,
    marksPerQuestion: 1,
    negativeMark: 0.25,
    youtubeQuery: "RBI Grade B ESI economics and social issues preparation",
    questions: [
      { id: 1, text: "Which inflation index is used by the RBI as the primary anchor for its Monetary Policy decisions?", options: { A: "Wholesale Price Index (WPI)", B: "Consumer Price Index — Combined (CPI-C)", C: "GDP Deflator", D: "Index of Industrial Production (IIP)" }, correct: "B", explanation: "Following the recommendations of the Urjit Patel Committee in 2014, the RBI officially adopted CPI (Combined) with base year 2012 as its key policy anchor." },
      { id: 2, text: "Under the flexible inflation targeting framework, what is the mandated inflation target for RBI?", options: { A: "3% with a band of +/- 1%", B: "4% with a tolerance band of +/- 2% (2% to 6%)", C: "5% with a tolerance band of +/- 2%", D: "Fixed 4% without any band" }, correct: "B", explanation: "Under Section 45ZA of the RBI Act 1934, the inflation target is 4% with an upper tolerance of 6% and lower tolerance of 2%." },
      { id: 3, text: "The term 'Stagflation' refers to a macroeconomic situation characterized by:", options: { A: "High economic growth accompanied by high inflation", B: "Stagnant economic growth accompanied by high unemployment and high inflation", C: "Deflation accompanied by negative interest rates", D: "High fiscal deficit with declining forex reserves" }, correct: "B", explanation: "Stagflation combines slow economic growth (stagnation) and relatively high unemployment with rising prices (inflation)." },
      { id: 4, text: "The difference between Total Revenue Receipts and Total Revenue Expenditure is known as:", options: { A: "Fiscal Deficit", B: "Revenue Deficit", C: "Primary Deficit", D: "Monetized Deficit" }, correct: "B", explanation: "Revenue Deficit = Revenue Expenditure - Revenue Receipts. It reflects that the government is borrowing to finance day-to-day administrative consumption." },
      { id: 5, text: "Primary Deficit is calculated as:", options: { A: "Fiscal Deficit minus Interest Payments", B: "Revenue Deficit minus Capital Outlay", C: "Gross Fiscal Deficit plus Net Lending", D: "Budget Deficit minus Disinvestment" }, correct: "A", explanation: "Primary Deficit = Fiscal Deficit - Interest Payments. It indicates the borrowing requirements of the government excluding past interest liabilities." },
      { id: 6, text: "What is the base year for the calculation of Consumer Price Index (CPI) in India?", options: { A: "2004-05", B: "2011-12", C: "2012", D: "2016" }, correct: "C", explanation: "The base year for CPI (Rural, Urban, Combined) compiled by NSO (National Statistics Office) is calendar year 2012 = 100." },
      { id: 7, text: "Which organization is responsible for releasing the Wholesale Price Index (WPI) in India?", options: { A: "RBI", B: "Central Statistical Office (NSO)", C: "Office of the Economic Adviser, Ministry of Commerce & Industry", D: "Ministry of Finance" }, correct: "C", explanation: "WPI data is compiled and released monthly by the Office of the Economic Adviser (OEA), Department for Promotion of Industry and Internal Trade (DPIIT)." },
      { id: 8, text: "The FRBM Act was enacted in India in which year?", options: { A: "1999", B: "2001", C: "2003", D: "2008" }, correct: "C", explanation: "The Fiscal Responsibility and Budget Management (FRBM) Act was passed in 2003 to introduce financial discipline and reduce fiscal deficits." },
      { id: 9, text: "Which of the following creates 'High Powered Money' (Reserve Money / M0) in India?", options: { A: "Commercial Banks", B: "Reserve Bank of India & Government of India", C: "SEBI", D: "Life Insurance Corporation" }, correct: "B", explanation: "Reserve Money (M0) consists of currency in circulation, bankers' deposits with the RBI, and other deposits with the RBI." },
      { id: 10, text: "The Gini Coefficient is widely used as an economic metric to measure:", options: { A: "National Income Growth Rate", B: "Income and Wealth Inequality", C: "Currency Depreciation", D: "Poverty Line Headcount Ratio" }, correct: "B", explanation: "The Gini Coefficient ranges from 0 (perfect equality) to 1 (maximal inequality) and is derived from the Lorenz Curve." },
      { id: 11, text: "In the context of banking, what is Basel III's Minimum Capital to Risk-Weighted Assets Ratio (CRAR) prescribed for Indian scheduled commercial banks by RBI?", options: { A: "8%", B: "9%", C: "11.5% (including CCB)", D: "14%" }, correct: "C", explanation: "While BCBS prescribes 10.5% (8% minimum + 2.5% CCB), RBI mandates a more conservative 9% minimum + 2.5% Capital Conservation Buffer = 11.5%." },
      { id: 12, text: "The 'Prompt Corrective Action' (PCA) framework is invoked by the RBI when banks breach thresholds on:", options: { A: "Capital, Asset Quality (Net NPA), and Leverage", B: "Branch count and employee turnover", C: "Share price and market capitalization", D: "Foreign currency deposits only" }, correct: "A", explanation: "PCA framework tracks Capital Adequacy (CRAR), Asset Quality (Net NPA ratio), and Leverage ratio to intervene before a bank fails." },
      { id: 13, text: "What constitutes the largest component of India's Foreign Exchange Reserves?", options: { A: "Gold", B: "Special Drawing Rights (SDRs)", C: "Foreign Currency Assets (FCA)", D: "Reserve Tranche Position in the IMF" }, correct: "C", explanation: "Foreign Currency Assets (comprising US Dollars, Euros, Yen, and sovereign bonds) account for more than 85% of total forex reserves." },
      { id: 14, text: "Which Committee proposed the concept of 'Universal Banks' in India?", options: { A: "Narasimham Committee II", B: "R.H. Khan Committee", C: "Nachiket Mor Committee", D: "Bimal Jalan Committee" }, correct: "B", explanation: "The R.H. Khan Committee (1998) recommended the concept of Universal Banking where development financial institutions (DFIs) and banks could engage in comprehensive banking services." },
      { id: 15, text: "Under the Pradhan Mantri Jan Dhan Yojana (PMJDY), what is the overdraft facility available to eligible account holders?", options: { A: "₹5,000", B: "₹10,000", C: "₹20,000", D: "₹25,000" }, correct: "B", explanation: "The overdraft facility under PMJDY was doubled from ₹5,000 to ₹10,000 with the age limit increased to 18-65 years." },
      { id: 16, text: "The Monetary Policy rate corridor has which rate at its lower bound?", options: { A: "Marginal Standing Facility (MSF)", B: "Standing Deposit Facility (SDF)", C: "Bank Rate", D: "Repo Rate" }, correct: "B", explanation: "In 2022, RBI introduced SDF (Standing Deposit Facility) at 25 bps below the Repo Rate as the new floor of the liquidity adjustment facility corridor." },
      { id: 17, text: "What is 'Headline Inflation'?", options: { A: "Inflation measured excluding volatile food and fuel items", B: "Total inflation in an economy including food, fuel and all commodities", C: "Inflation recorded in stock market assets", D: "Inflation measured exclusively for luxury products" }, correct: "B", explanation: "Headline Inflation covers the full basket of consumer goods including volatile food and fuel. When food and energy are excluded, it is called 'Core Inflation'." },
      { id: 18, text: "The term 'Sovereign Green Bonds' issued by the Government of India are earmarked for financing:", options: { A: "Fiscal deficit reduction directly", B: "Public sector projects that reduce carbon intensity and promote green energy", C: "Defence equipment manufacturing", D: "Disinvestment receipts" }, correct: "B", explanation: "Sovereign Green Bonds mobilize funds for green infrastructure projects like solar parks, wind power, and public transit that lower carbon emissions." },
      { id: 19, text: "Which institution acts as the regulator for Pension Funds in India?", options: { A: "IRDAI", B: "SEBI", C: "PFRDA", D: "EPFO" }, correct: "C", explanation: "PFRDA (Pension Fund Regulatory and Development Authority) was established under the PFRDA Act 2013 to regulate NPS and pension schemes." },
      { id: 20, text: "The concept of 'Liquidity Trap' in Keynesian economics occurs when:", options: { A: "Interest rates are very high and people invest heavily in bonds", B: "Interest rates fall close to zero and monetary policy becomes ineffective as people hoard cash", C: "Commercial banks experience an acute run on deposits", D: "Government bans cash transactions" }, correct: "B", explanation: "In a liquidity trap, nominal interest rates approach zero, demand for money becomes perfectly elastic, and injecting cash fails to stimulate lending or investment." },
    ]
  },

  {
    slug: "upsc-csat-reasoning",
    title: "UPSC CSAT — Logical Reasoning & Analytical Ability",
    description: "20 high-standard CSAT questions covering syllogisms, seating arrangements, assumptions, and critical reasoning.",
    examType: "UPSC",
    topic: "CSAT Paper II",
    difficulty: "Hard",
    durationMinutes: 25,
    totalQuestions: 20,
    marksPerQuestion: 2.5,
    negativeMark: 0.83,
    youtubeQuery: "UPSC CSAT prelims paper 2 reasoning preparation strategy",
    questions: [
      { id: 1, text: "Consider the statements: (1) All fruits are sweet. (2) No sweet is healthy. Which conclusion logically follows?", options: { A: "All fruits are healthy", B: "No fruit is healthy", C: "Some healthy items are fruits", D: "All healthy items are sweet" }, correct: "B", explanation: "Since All Fruits are in Sweet, and No Sweet is Healthy, Fruits and Healthy sets are mutually disjoint. Therefore, 'No fruit is healthy' is valid." },
      { id: 2, text: "Five friends A, B, C, D, and E are sitting in a circle facing the center. A is to the immediate right of B. E is between D and B. Who is sitting to the immediate left of C?", options: { A: "A", B: "D", C: "B", D: "E" }, correct: "B", explanation: "Arranging clockwise from B: B, A, C, D, E. To the immediate left of C (facing center) is D." },
      { id: 3, text: "If 'P + Q' means P is the mother of Q; 'P - Q' means P is the brother of Q; 'P × Q' means P is the father of Q. Which of the following shows that M is the maternal uncle of N?", options: { A: "M - K + N", B: "M + K - N", C: "M × K + N", D: "M - K × N" }, correct: "A", explanation: "M - K means M is brother of K. K + N means K is mother of N. Thus M is the brother of N's mother, which means M is maternal uncle of N." },
      { id: 4, text: "In a code language, 'ROSE' is written as '6821' and 'CHAIR' is written as '73456'. What will 'SEARCH' be written as?", options: { A: "214673", B: "214573", C: "214637", D: "216473" }, correct: "A", explanation: "Matching letters: S=2, E=1, A=4, R=6, C=7, H=3. Hence SEARCH = 214673." },
      { id: 5, text: "Statement: 'The municipal corporation advised citizens to boil water before drinking as a precautionary measure.' Assumptions: (I) People may heed the advisory. (II) Boiling water kills harmful pathogens.", options: { A: "Only I is implicit", B: "Only II is implicit", C: "Both I and II are implicit", D: "Neither I nor II is implicit" }, correct: "C", explanation: "Any public advisory assumes both that the public is capable of complying (I) and that the action serves its stated scientific purpose (II)." },
      { id: 6, text: "Pointing to a photograph, Rohit said: 'She is the daughter of my grandfather's only son.' How is the girl in the photograph related to Rohit?", options: { A: "Sister", B: "Mother", C: "Cousin", D: "Aunt" }, correct: "A", explanation: "Rohit's grandfather's only son is Rohit's father. The daughter of Rohit's father is Rohit's sister." },
      { id: 7, text: "Six books P, Q, R, S, T, and U are stacked one above another. R is just above S. T is between P and Q. U is at the top. P is just below R. Which book is at the bottom?", options: { A: "S", B: "Q", C: "P", D: "T" }, correct: "B", explanation: "Arranging from top: U, R, S, P, T, Q. Therefore, book Q is at the bottom." },
      { id: 8, text: "If yesterday was Tuesday, what day of the week will it be 100 days from today?", options: { A: "Thursday", B: "Friday", C: "Saturday", D: "Sunday" }, correct: "A", explanation: "Yesterday was Tuesday, so today is Wednesday. 100 mod 7 = 2 odd days. Wednesday + 2 days = Friday? Wait: 100 = 14*7 + 2. Wednesday + 1 = Thursday, Wednesday + 2 = Friday. Wait, let's verify: 7 days from Wed is Wed. 98 days from Wed is Wed. 99 is Thu, 100 is Fri. Ah, option B is Friday!" },
      { id: 9, text: "Two statements are given: (1) Some poets are dreamers. (2) All dreamers are philosophers. Which conclusion follows?", options: { A: "All philosophers are dreamers", B: "Some poets are philosophers", C: "No poet is a philosopher", D: "All poets are philosophers" }, correct: "B", explanation: "Some poets are dreamers (I), and all dreamers are philosophers (A). I + A = I. Hence, Some poets are philosophers." },
      { id: 10, text: "A clock shows 4:20. What is the angle between the hour hand and the minute hand?", options: { A: "0 degrees", B: "10 degrees", C: "15 degrees", D: "20 degrees" }, correct: "B", explanation: "Angle = |30H - 5.5M| = |30(4) - 5.5(20)| = |120 - 110| = 10 degrees." },
      { id: 11, text: "If north becomes north-east, and west becomes north-west, what will south become?", options: { A: "South-East", B: "South-West", C: "East", D: "North" }, correct: "B", explanation: "Every direction rotates 45 degrees clockwise. South rotated 45 degrees clockwise becomes South-West." },
      { id: 12, text: "Statement: 'Should road toll taxes be abolished on national highways?' Argument I: 'Yes, citizens already pay income and fuel taxes.' Argument II: 'No, toll revenues are vital for maintenance and highway expansion.'", options: { A: "Only I is strong", B: "Only II is strong", C: "Both I and II are strong", D: "Neither I nor II is strong" }, correct: "B", explanation: "Argument II is economically and operationally sound because user-fee principles are necessary for modern capital-intensive highway infrastructure." },
      { id: 13, text: "Find the missing number in the sequence: 3, 7, 15, 31, 63, ?", options: { A: "127", B: "125", C: "129", D: "131" }, correct: "A", explanation: "Rule: 2x + 1. (3×2)+1=7, (7×2)+1=15, (15×2)+1=31, (31×2)+1=63, (63×2)+1 = 127." },
      { id: 14, text: "In a class of 60 students, 35 play cricket, 25 play football, and 10 play both. How many students play neither cricket nor football?", options: { A: "10", B: "12", C: "15", D: "20" }, correct: "A", explanation: "n(C ∪ F) = n(C) + n(F) - n(C ∩ F) = 35 + 25 - 10 = 50. Total who play neither = 60 - 50 = 10." },
      { id: 15, text: "A is taller than B, but shorter than C. D is taller than E, but shorter than B. Who is the tallest among them all?", options: { A: "A", B: "B", C: "C", D: "D" }, correct: "C", explanation: "Relationships: C > A > B > D > E. Hence, C is the tallest." },
      { id: 16, text: "Which year will have the same calendar as the year 2025?", options: { A: "2031", B: "2036", C: "2030", D: "2029" }, correct: "A", explanation: "For a regular year that comes after a leap year (2025 comes after 2024), the calendar repeats after 6 years: 2025 + 6 = 2031." },
      { id: 17, text: "Statement: 'A large number of students failed in the final semester engineering exams.' Action I: 'The university should conduct remedial coaching classes.' Action II: 'The university should cancel the exam system.'", options: { A: "Only I follows", B: "Only II follows", C: "Both I and II follow", D: "Neither follows" }, correct: "A", explanation: "Action I is constructive and addresses the learning deficiency, whereas cancelling exams is disproportionate and irrational." },
      { id: 18, text: "How many triangles are there in a standard pentagram (5-pointed star)?", options: { A: "8", B: "10", C: "12", D: "15" }, correct: "B", explanation: "A 5-pointed star has 5 outer small triangles and 5 larger overlapping triangles created by each vertex and two inner intersections, making 10 in total." },
      { id: 19, text: "If 'TABLE' is coded as 'GZYOV', how is 'CHAIR' coded?", options: { A: "XSZRI", B: "XSZIR", C: "XTSIR", D: "WSZRI" }, correct: "A", explanation: "Each letter is paired with its reverse alphabetical counterpart (A-Z, B-Y, C-X, H-S, A-Z, I-R, R-I). Hence, CHAIR = XSZRI." },
      { id: 20, text: "A cube of 4 cm side is painted red on all sides and cut into smaller cubes of 1 cm side each. How many small cubes will have NO face painted?", options: { A: "4", B: "8", C: "12", D: "16" }, correct: "B", explanation: "Number of cubes with zero painted faces = (n - 2)³ where n = 4/1 = 4. (4 - 2)³ = 2³ = 8 cubes." },
    ]
  }
];

let fileContent = fs.readFileSync('./src/lib/mockTestsData.js', 'utf8');

// Insert new tests before the closing bracket of MOCK_TESTS
const insertIdx = fileContent.lastIndexOf('export function getTestBySlug');
const splitPoint = fileContent.lastIndexOf(']', insertIdx);

const newTestsCode = NEW_TESTS.map(t => ',\n  ' + JSON.stringify(t, null, 2)).join('');
fileContent = fileContent.slice(0, splitPoint) + newTestsCode + '\n' + fileContent.slice(splitPoint);

fs.writeFileSync('./src/lib/mockTestsData.js', fileContent, 'utf8');
console.log('Successfully expanded mockTestsData.js with 5 new tests!');
