// ============================================================
// lib/currentAffairsData.js — Seed current affairs entries
// ExamUdaan.in — 30 curated entries for MPSC/UPSC/Banking/SSC
// Phase 1: static file | Phase 2: scraper feeds DB
// ============================================================

export const CURRENT_AFFAIRS = [
  // ── September 2026 ─────────────────────────────────────────
  {
    id: 1,
    slug: "india-gdp-4-trillion-2025",
    date: "2026-09-20",
    title: "India's GDP Crosses $4 Trillion — Becomes World's 4th Largest Economy",
    summary: "India's nominal GDP has surpassed $4 trillion, overtaking Japan to become the world's 4th largest economy. The milestone was achieved ahead of projections, driven by strong manufacturing growth, IT exports, and infrastructure investment under PM Gati Shakti.",
    category: "Economy",
    examTags: ["MPSC", "UPSC", "Banking", "SSC"],
    whyItMatters: "For UPSC/MPSC: GDP milestones are frequently asked in GS Paper III (Economy). India's economic trajectory, target of $5 trillion by 2027, and comparison with China/USA are key focus areas.",
    sourceUrl: "https://pib.gov.in/",
    sourceName: "PIB India",
    youtubeQuery: "India GDP 4 trillion economy UPSC MPSC",
  },
  {
    id: 2,
    slug: "atal-setu-mumbai-facts",
    date: "2026-09-19",
    title: "Atal Setu (MTHL) — Key Facts Every Maharashtra Aspirant Must Know",
    summary: "The Mumbai Trans Harbour Link (Atal Setu), inaugurated January 2024, is India's longest sea bridge at 21.8 km. It connects Sewri (Mumbai) to Nhava Sheva (Navi Mumbai), reducing travel time from 60 minutes to 20 minutes. Built at a cost of ₹17,843 crore.",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti"],
    whyItMatters: "MPSC and Police Bharti frequently ask about Maharashtra infrastructure projects. Atal Setu length (21.8 km), cost, and what it connects are likely MCQ targets.",
    sourceUrl: "https://maharashtra.gov.in/",
    sourceName: "Maharashtra Government",
    youtubeQuery: "Atal Setu Mumbai Trans Harbour Link MPSC",
  },
  {
    id: 3,
    slug: "rbi-repo-rate-cut-2025",
    date: "2026-09-18",
    title: "RBI Cuts Repo Rate to 6.25% — What It Means for You",
    summary: "The Reserve Bank of India's Monetary Policy Committee (MPC) reduced the repo rate from 6.5% to 6.25% in its February 2025 meeting — the first rate cut in 5 years. This signals an accommodative stance as retail inflation (CPI) came below the 4% target.",
    category: "Economy",
    examTags: ["IBPS", "Banking", "MPSC", "UPSC"],
    whyItMatters: "Banking awareness section of IBPS/SBI exams: Repo Rate, Reverse Repo Rate, CRR, SLR are always asked. Understanding rate cuts + impact on EMIs + monetary policy is essential.",
    sourceUrl: "https://rbi.org.in/",
    sourceName: "Reserve Bank of India",
    youtubeQuery: "RBI repo rate cut 2025 IBPS banking awareness",
  },
  {
    id: 4,
    slug: "chandrayaan-3-anniversary-2025",
    date: "2026-09-17",
    title: "Chandrayaan-3 — India's Moon Mission: Complete Facts for Exam",
    summary: "On 23 August 2023, India became the first country to land near the Moon's south pole (Shiv Shakti Point). Vikram lander and Pragyan rover operated for 14 Earth days. The mission cost ₹615 crore — less than many Hollywood films. ISRO achieved this in the 4th attempt.",
    category: "Science & Tech",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "Space missions are frequently asked in SSC CGL, MPSC, and UPSC Prelims. Key facts: landing site name (Shiv Shakti Point), date (23 Aug 2023), rover name (Pragyan), lander name (Vikram), cost (₹615 crore).",
    sourceUrl: "https://isro.gov.in/",
    sourceName: "ISRO",
    youtubeQuery: "Chandrayaan 3 facts UPSC SSC exam preparation",
  },
  {
    id: 5,
    slug: "one-nation-one-election-bill",
    date: "2026-09-16",
    title: "One Nation One Election — Parliament Committee Report 2024",
    summary: "The Joint Parliamentary Committee (JPC) submitted its report on the Constitution (129th Amendment) Bill proposing simultaneous elections for Lok Sabha and all State Assemblies. The bill proposes a unified election cycle starting 2029. Former President Kovind chaired the original committee.",
    category: "National",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "UPSC/MPSC Polity: Constitutional amendments, Parliament bills, and electoral reforms are key topics. 'One Nation One Election' has appeared in multiple CSE Prelims and MPSC questions.",
    sourceUrl: "https://sansad.in/",
    sourceName: "Sansad.in / Lok Sabha",
    youtubeQuery: "One Nation One Election bill explained UPSC MPSC polity",
  },
  {
    id: 6,
    slug: "mpsc-2026-notification-prelims",
    date: "2026-09-15",
    title: "MPSC Rajya Seva Pariksha 2026 — Prelims Notification Released",
    summary: "MPSC has released the official notification for Rajya Seva Pariksha (State Services Exam) 2026. The preliminary exam is scheduled for February 2026. Total vacancies: 312 (tentative). Application window: October–November 2026. Exam will be conducted via MAHAPARIKSHA portal.",
    category: "Maharashtra",
    examTags: ["MPSC"],
    whyItMatters: "Key dates for MPSC aspirants: Application start/end, Prelims date. Check official mpsc.gov.in for the most updated notification. Always carry Aadhaar for MAHAPARIKSHA registration.",
    sourceUrl: "https://mpsc.gov.in/",
    sourceName: "MPSC Official",
    youtubeQuery: "MPSC 2026 notification rajya seva pariksha preparation",
  },
  {
    id: 7,
    slug: "budget-2025-26-key-highlights",
    date: "2026-09-14",
    title: "Union Budget 2025-26 — Top 10 Highlights Every Aspirant Must Know",
    summary: "Finance Minister Nirmala Sitharaman presented the Union Budget 2025-26. Key announcements: (1) Zero income tax up to ₹12 lakh under new regime. (2) ₹11.11 lakh crore capital expenditure. (3) New Income Tax Bill replacing 1961 Act. (4) MSME credit guarantee enhanced. (5) PM Dhan Dhanya Krishi Yojana for 100 low-productivity districts.",
    category: "Economy",
    examTags: ["UPSC", "MPSC", "Banking", "SSC", "IBPS"],
    whyItMatters: "Union Budget is a GOLD MINE for current affairs questions. Every major exam asks about budget allocations, new schemes, and tax changes. The ₹12 lakh tax exemption is the most likely MCQ target.",
    sourceUrl: "https://indiabudget.gov.in/",
    sourceName: "India Budget Portal",
    youtubeQuery: "Union Budget 2025-26 highlights UPSC MPSC key points",
  },
  {
    id: 8,
    slug: "maharashtra-ladki-bahin-yojana",
    date: "2026-09-13",
    title: "Mukhyamantri Majhi Ladki Bahin Yojana — Complete Details",
    summary: "Maharashtra government's flagship welfare scheme provides ₹1,500 per month to women aged 21–65 years from families with annual income below ₹2.5 lakh. The scheme was launched August 2024. As of 2025, over 2.5 crore women are enrolled. Budget allocation: ₹46,000 crore annually.",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti"],
    whyItMatters: "Maharashtra welfare schemes are heavily tested in MPSC Prelims and Police Bharti. Know: amount (₹1,500/month), eligibility (age 21-65, income < ₹2.5L), launch year (2024), enrolled count (2.5 crore+).",
    sourceUrl: "https://maharashtra.gov.in/",
    sourceName: "Maharashtra Government",
    youtubeQuery: "Ladki Bahin Yojana Maharashtra MPSC government scheme",
  },
  {
    id: 9,
    slug: "india-upi-16-billion-transactions",
    date: "2026-09-12",
    title: "UPI Crosses 16 Billion Monthly Transactions — India's FinTech Triumph",
    summary: "India's UPI (Unified Payments Interface) processed over 16 billion transactions worth ₹20+ lakh crore in a single month in 2025, making India the global leader in real-time digital payments. UPI now operates in 7+ countries including UAE, Singapore, France, and Nepal.",
    category: "Economy",
    examTags: ["Banking", "IBPS", "UPSC"],
    whyItMatters: "IBPS/SBI Banking Awareness: UPI, NPCI, digital payments are frequently asked. Key stats: 16 billion transactions/month, governed by NPCI, interoperable across 50+ banks.",
    sourceUrl: "https://npci.org.in/",
    sourceName: "NPCI India",
    youtubeQuery: "UPI transactions 2025 banking awareness IBPS",
  },
  {
    id: 10,
    slug: "viksit-bharat-2047-vision",
    date: "2026-09-11",
    title: "Viksit Bharat 2047 — India's Vision for the Centenary of Independence",
    summary: "The Government of India's 'Viksit Bharat 2047' initiative aims to make India a fully developed nation (per capita income > $12,000) by the centenary of independence. Key pillars: (1) Economic Growth, (2) Infrastructure, (3) Inclusion, (4) Innovation. The initiative has received over 1.4 crore suggestions from citizens.",
    category: "National",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "UPSC Essay and GS Paper II: National development goals, governance, and long-term vision are important. 'Viksit Bharat 2047' and its four pillars may be asked in essay/mains.",
    sourceUrl: "https://viksitbharat.gov.in/",
    sourceName: "Viksit Bharat Portal",
    youtubeQuery: "Viksit Bharat 2047 vision UPSC essay topic",
  },
  {
    id: 11,
    slug: "agni-5-mirv-mission-divyastra",
    date: "2026-09-10",
    title: "Mission Divyastra — India Tests Agni-V MIRV Missile",
    summary: "India successfully tested Agni-V with MIRV (Multiple Independently Targetable Re-entry Vehicle) technology, code-named 'Mission Divyastra,' in March 2024. This makes India the 4th country with MIRV capability after USA, Russia, and China. Range: 5,000+ km. Developed by DRDO.",
    category: "Science & Tech",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "Defence technology is a key current affairs area for UPSC and SSC. MIRV means one missile can carry multiple warheads targeting different locations — strategic deterrence against adversaries.",
    sourceUrl: "https://drdo.gov.in/",
    sourceName: "DRDO India",
    youtubeQuery: "Mission Divyastra Agni-V MIRV India defence UPSC",
  },
  {
    id: 12,
    slug: "pm-kusum-scheme-solar-farmers",
    date: "2026-09-09",
    title: "PM-KUSUM Scheme — Solar Pumps for 35 Lakh Farmers by 2026",
    summary: "PM Kisan Urja Suraksha evam Utthaan Mahabhiyan (PM-KUSUM) aims to install 35 lakh solar-powered agricultural pump sets and 10,000 MW of solar capacity on barren land by farmers. Maharashtra has been one of the top implementing states with 3.5 lakh solar pumps installed.",
    category: "National",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "Government schemes for agriculture are frequently asked in MPSC and UPSC. PM-KUSUM components: A (barren land solar), B (standalone solar pumps), C (grid-connected solar). Maharashtra's implementation is a bonus fact.",
    sourceUrl: "https://pmkusum.mnre.gov.in/",
    sourceName: "MNRE / PM-KUSUM",
    youtubeQuery: "PM KUSUM yojana solar farmers MPSC UPSC government schemes",
  },
  {
    id: 13,
    slug: "maharashtra-samruddhi-highway",
    date: "2026-09-08",
    title: "Samruddhi Mahamarg — Hindu Hrudaysamrat Balasaheb Thackeray Maharashtra Samruddhi Highway",
    summary: "India's longest highway (701 km) connects Nagpur to Mumbai via Shirdi. Fully operational since 2023, the 8-lane expressway reduces Nagpur-Mumbai travel time from 14 hours to 8 hours. 24 access points, 3 wildlife crossings. Built at a cost of ₹55,000+ crore by MSRDC.",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti"],
    whyItMatters: "MPSC & Police Bharti: Maharashtra infrastructure projects are regularly tested. Key facts: length (701 km), Nagpur to Mumbai, 8-lane, ₹55,000 crore cost, built by MSRDC.",
    sourceUrl: "https://msrdc.org/",
    sourceName: "MSRDC",
    youtubeQuery: "Samruddhi Mahamarg expressway MPSC Maharashtra facts",
  },
  {
    id: 14,
    slug: "india-semiconductor-mission-2025",
    date: "2026-09-07",
    title: "India Semiconductor Mission — ₹76,000 Crore Push for Chip Manufacturing",
    summary: "The Union Cabinet has approved three semiconductor fabrication plants under India Semiconductor Mission (ISM): Tata Electronics in Dholera (Gujarat), CG Power in Sanand (Gujarat), and Kaynes Semicon in Sanand. Combined investment: ₹1.52 lakh crore. Expected to create 60,000 direct jobs.",
    category: "Science & Tech",
    examTags: ["UPSC", "SSC", "Banking"],
    whyItMatters: "UPSC GS Paper III (Technology): India's push into semiconductor manufacturing reduces import dependency. Semiconductors are critical for electronics, defence, and EV sectors.",
    sourceUrl: "https://pib.gov.in/",
    sourceName: "PIB India",
    youtubeQuery: "India semiconductor mission chips manufacturing UPSC",
  },
  {
    id: 15,
    slug: "nobel-peace-prize-2024-nihon-hidankyo",
    date: "2026-09-06",
    title: "Nobel Peace Prize 2024 — Nihon Hidankyo (Japan Atomic Bomb Survivors)",
    summary: "The 2024 Nobel Peace Prize was awarded to Nihon Hidankyo, a Japanese grassroots organization of atomic bomb survivors (Hibakusha) from Hiroshima and Nagasaki. The award recognizes their efforts to achieve a world free from nuclear weapons through personal testimony and advocacy.",
    category: "International",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "Nobel Prizes are static GK for SSC CGL, MPSC, and UPSC. Nobel Peace Prize winner (year + recipient + reason) is almost always asked in the following year's exams.",
    sourceUrl: "https://nobelprize.org/",
    sourceName: "Nobel Prize Organization",
    youtubeQuery: "Nobel Prize 2024 winners list UPSC SSC current affairs",
  },
  {
    id: 16,
    slug: "india-stack-g20-digital-public-infra",
    date: "2026-09-05",
    title: "India Stack — DPI (Digital Public Infrastructure) Goes Global via G20",
    summary: "India's Digital Public Infrastructure (India Stack) — comprising Aadhaar, UPI, DigiLocker, and ONDC — has been recognized as a model by G20 nations. Over 100 countries have shown interest in replicating India's DPI framework. India has exported its UPI infrastructure to 7+ countries.",
    category: "Economy",
    examTags: ["UPSC", "MPSC", "Banking", "IBPS"],
    whyItMatters: "India's fintech and digital governance success is a key UPSC GS II topic. DPI components (Aadhaar ID + UPI payments + DigiLocker documents + ONDC commerce) = India Stack.",
    sourceUrl: "https://indiastack.org/",
    sourceName: "IndiaStack",
    youtubeQuery: "India stack DPI digital public infrastructure UPSC G20",
  },
  {
    id: 17,
    slug: "cop29-baku-climate-2024",
    date: "2026-09-04",
    title: "COP29 — Baku, Azerbaijan (November 2024): Key Outcomes for India",
    summary: "COP29 (29th Conference of Parties to UNFCCC) was held in Baku, Azerbaijan in November 2024. Key outcome: New Collective Quantified Goal (NCQG) — developed nations to provide $300 billion/year by 2035 to developing nations for climate action. India secured a commitment for technology transfer.",
    category: "Environment",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "UPSC GS Paper III Environment: COP meetings, UNFCCC, Paris Agreement, NCQG, and India's climate commitments (NDC targets, net zero by 2070) are important recurring topics.",
    sourceUrl: "https://unfccc.int/",
    sourceName: "UNFCCC",
    youtubeQuery: "COP29 Baku climate change UPSC environment current affairs",
  },
  {
    id: 18,
    slug: "maharashtra-assembly-election-2024-result",
    date: "2026-09-03",
    title: "Maharashtra Assembly Elections 2024 — Mahayuti Wins Decisive Majority",
    summary: "Mahayuti (BJP + Shiv Sena Shinde + NCP Ajit Pawar) won 230 out of 288 seats in the Maharashtra Assembly Election 2024, a historic majority. BJP emerged as the single largest party with 132 seats. Devendra Fadnavis was sworn in as Chief Minister. Mahayutti's Ladki Bahin Yojana was credited as a key factor.",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti"],
    whyItMatters: "MPSC: Current Chief Minister, state government composition, and recent election results are asked in Maharashtra GK sections. Remember: Devendra Fadnavis (CM), Eknath Shinde + Ajit Pawar (Deputy CMs).",
    sourceUrl: "https://election.maharashtra.gov.in/",
    sourceName: "Maharashtra Election Commission",
    youtubeQuery: "Maharashtra election 2024 result Mahayuti MPSC current affairs",
  },
  {
    id: 19,
    slug: "india-china-patrolling-agreement-lac",
    date: "2026-09-02",
    title: "India-China LAC Patrolling Agreement — October 2024 Deal",
    summary: "India and China reached an agreement in October 2024 to restore patrolling rights along the Line of Actual Control (LAC) at Depsang and Demchok in Ladakh — areas that had been disengaged since the 2020 Galwan Valley clash. The agreement was announced before PM Modi's meeting with Chinese President Xi Jinping at the BRICS Summit.",
    category: "International",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "UPSC IR (International Relations): India-China border disputes, LAC, Galwan clash (June 2020), and the 2024 patrolling deal are important for GS Paper II and current affairs.",
    sourceUrl: "https://mea.gov.in/",
    sourceName: "Ministry of External Affairs",
    youtubeQuery: "India China LAC patrolling agreement 2024 UPSC international relations",
  },
  {
    id: 20,
    slug: "india-maldives-bilateral-2024",
    date: "2026-09-01",
    title: "India-Maldives Relations — Troops Withdrawal, Infrastructure & Economic Aid",
    summary: "India withdrew its military personnel from Maldives in May 2024 as requested by President Muizzu, replacing them with civilian technical staff. Despite the diplomatic tension, India remains Maldives' largest trade partner, provided $50 million in budget support, and is building the Greater Male Connectivity Project bridge.",
    category: "International",
    examTags: ["UPSC"],
    whyItMatters: "UPSC IR: India's 'Neighbourhood First' policy, SAARC relations, and the India-Maldives dynamic (strategic Indian Ocean + tourism economy) are important themes for GS Paper II.",
    sourceUrl: "https://mea.gov.in/",
    sourceName: "Ministry of External Affairs",
    youtubeQuery: "India Maldives relations 2024 UPSC neighbourhood first policy",
  },
  {
    id: 21,
    slug: "maharashtra-nagpur-metro-phase2",
    date: "2026-08-30",
    title: "Nagpur Metro Phase 2 — Expansion to Cover 48 km New Routes",
    summary: "Nagpur Metro Phase 2 has been approved with 48 km of new metro corridors, adding 36 new stations across the city. The ₹6,708 crore project will connect Hingna, Butibori industrial area, and the airport to the existing Phase 1 network by 2028.",
    category: "Maharashtra",
    examTags: ["MPSC"],
    whyItMatters: "Maharashtra infrastructure: Nagpur Metro (Maharashtra Metro Rail Corporation) expansion, cost, and route coverage are testable facts for MPSC and Maharashtra GK sections.",
    sourceUrl: "https://metrorailnagpur.com/",
    sourceName: "Maharashtra Metro Rail Corporation",
    youtubeQuery: "Nagpur Metro Phase 2 Maharashtra infrastructure MPSC",
  },
  {
    id: 22,
    slug: "india-ranked-5th-renewable-energy",
    date: "2026-08-28",
    title: "India 4th in Global Renewable Energy Capacity — 200 GW Solar Target 2026",
    summary: "India has reached 4th position globally in renewable energy capacity with over 200 GW of installed capacity (solar + wind + hydro). The government targets 500 GW of non-fossil fuel capacity by 2030. National Solar Mission aims for 280 GW solar by 2030.",
    category: "Environment",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "UPSC GS III (Environment): India's renewable energy goals, Solar Mission, Wind Mission, and India's NDC commitments are key. '500 GW by 2030' is a frequently asked target.",
    sourceUrl: "https://mnre.gov.in/",
    sourceName: "MNRE India",
    youtubeQuery: "India renewable energy capacity 2025 solar UPSC environment",
  },
  {
    id: 23,
    slug: "ibps-rrb-2026-notification",
    date: "2026-08-25",
    title: "IBPS RRB 2026 — Notification Released for Officer Scale I, II, III & Office Assistant",
    summary: "IBPS has released notification for RRB (Regional Rural Banks) 2026 recruitment for 9,000+ vacancies across Officer Scale I, II, III, and Office Assistants. Online applications open August 2026. Maharashtra aspirants can apply for banks like Maharashtra Gramin Bank, Vidarbha-Konkan Gramin Bank.",
    category: "National",
    examTags: ["IBPS", "Banking"],
    whyItMatters: "IBPS RRB is an excellent opportunity for Maharashtra aspirants — it has Marathi language preference, interviews are in local language, and competition is lower than IBPS PO.",
    sourceUrl: "https://ibps.in/",
    sourceName: "IBPS Official",
    youtubeQuery: "IBPS RRB 2026 notification preparation strategy",
  },
  {
    id: 24,
    slug: "india-china-brics-summit-2024",
    date: "2026-08-22",
    title: "BRICS Summit 2024 — Kazan, Russia: India's Key Positions",
    summary: "The 2024 BRICS Summit was held in Kazan, Russia in October 2024. 9 new members joined BRICS: Egypt, Ethiopia, Iran, Saudi Arabia, UAE, Argentina (declined), Indonesia, Malaysia, and Cuba (observer). PM Modi met President Putin and Xi Jinping. India pushed for BRICS payment system reform.",
    category: "International",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "UPSC IR: BRICS expansion, member countries, India's role, and alternative payment systems to SWIFT are important topics. New BRICS members is a guaranteed MCQ.",
    sourceUrl: "https://mea.gov.in/",
    sourceName: "MEA India",
    youtubeQuery: "BRICS 2024 Kazan summit new members UPSC current affairs",
  },
  {
    id: 25,
    slug: "maharashtra-water-conservation-jalyukt-shivar",
    date: "2026-08-20",
    title: "Jalyukt Shivar 2.0 — Maharashtra Water Conservation Scheme Revived",
    summary: "Maharashtra government revived Jalyukt Shivar Abhiyan 2.0 — a water conservation scheme targeting 5,000 villages across drought-prone Marathwada and Vidarbha. The scheme creates farm ponds, deepens rivers, and builds check dams to make villages water-sufficient (zero tanker dependency).",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti"],
    whyItMatters: "MPSC: Maharashtra government schemes for water conservation and drought relief are regularly tested. Jalyukt Shivar = water storage + rural employment + farmer welfare.",
    sourceUrl: "https://maharashtra.gov.in/",
    sourceName: "Maharashtra Government",
    youtubeQuery: "Jalyukt Shivar 2.0 Maharashtra water conservation MPSC scheme",
  },
  {
    id: 26,
    slug: "india-spacex-nasa-astronaut-shubhanshu-shukla",
    date: "2026-08-18",
    title: "ISRO's Shubhanshu Shukla to Fly to ISS — Axiom Space Mission 4",
    summary: "IAF Group Captain Shubhanshu Shukla has been selected as India's first astronaut to fly to the International Space Station (ISS) via the Axiom Space Mission 4 (Ax-4) in 2025. He will conduct microgravity research experiments and represent India's growing human spaceflight program ahead of Gaganyaan.",
    category: "Science & Tech",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "Space missions are favourite current affairs questions. Know: Shubhanshu Shukla (IAF), Axiom Mission 4, ISS, and Gaganyaan (India's own human spaceflight mission — 2026 target).",
    sourceUrl: "https://isro.gov.in/",
    sourceName: "ISRO India",
    youtubeQuery: "India ISS mission Shubhanshu Shukla ISRO astronaut UPSC",
  },
  {
    id: 27,
    slug: "india-new-criminal-laws-bnss-bns-bsa",
    date: "2026-08-15",
    title: "BNS, BNSS, BSA — India's 3 New Criminal Laws Replace IPC, CrPC, Evidence Act",
    summary: "From 1 July 2024, three new criminal laws replaced India's colonial-era codes: (1) Bharatiya Nyaya Sanhita (BNS) replaced IPC 1860, (2) Bharatiya Nagarik Suraksha Sanhita (BNSS) replaced CrPC 1973, (3) Bharatiya Sakshya Adhiniyam (BSA) replaced Indian Evidence Act 1872. Key change: Sedition law removed; terrorism redefined.",
    category: "National",
    examTags: ["UPSC", "MPSC", "SSC", "Police Bharti"],
    whyItMatters: "Highly important for MPSC, UPSC, and Police Bharti. New names (BNS/BNSS/BSA) vs old (IPC/CrPC/Evidence Act), effective date (1 July 2024), and key changes are must-know facts.",
    sourceUrl: "https://mha.gov.in/",
    sourceName: "Ministry of Home Affairs",
    youtubeQuery: "BNS BNSS BSA new criminal laws India IPC CrPC UPSC MPSC police",
  },
  {
    id: 28,
    slug: "maharashtra-cm-devendra-fadnavis-cabinet-2024",
    date: "2026-08-12",
    title: "Maharashtra Cabinet 2024 — Key Ministers and Portfolios",
    summary: "After Mahayuti's victory in November 2024 elections: Chief Minister: Devendra Fadnavis (BJP). Deputy CMs: Eknath Shinde (Shiv Sena) and Ajit Pawar (NCP). Key portfolios: Home — Fadnavis, Finance — Ajit Pawar, Urban Development — Eknath Shinde, Agriculture — Fadnavis (held), Revenue — Chandrashekhar Bawankule.",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti"],
    whyItMatters: "MPSC: Current Maharashtra CM, Deputy CMs, and key portfolios are regularly asked. CM = Devendra Fadnavis, Deputy CMs = Eknath Shinde + Ajit Pawar.",
    sourceUrl: "https://maharashtra.gov.in/",
    sourceName: "Maharashtra Government",
    youtubeQuery: "Maharashtra cabinet 2024 Chief Minister Fadnavis MPSC",
  },
  {
    id: 29,
    slug: "india-defence-budget-2025-lakshya",
    date: "2026-08-10",
    title: "India's Defence Budget 2025-26 — ₹6.81 Lakh Crore; Highest Ever",
    summary: "India's defence budget for 2025-26 is ₹6.81 lakh crore — the highest ever and 2.4% of GDP. Capital expenditure (modernisation): ₹1.8 lakh crore. 75% of capital procurement must be from domestic companies under 'Atmanirbhar Bharat' (Make in India). Key acquisitions: MRFA fighter jets, submarines, Predator drones.",
    category: "National",
    examTags: ["UPSC", "SSC"],
    whyItMatters: "UPSC GS III (Security): Defence budget allocation, indigenisation targets (75% domestic procurement), and major defence deals are important. Atmanirbhar in defence is a key policy initiative.",
    sourceUrl: "https://mod.gov.in/",
    sourceName: "Ministry of Defence",
    youtubeQuery: "India defence budget 2025 Atmanirbhar UPSC national security",
  },
  {
    id: 30,
    slug: "ssc-cgl-2026-notification-10000-vacancies",
    date: "2026-08-08",
    title: "SSC CGL 2026 — 17,000+ Vacancies Notification Expected in October",
    summary: "Staff Selection Commission (SSC) is expected to release the Combined Graduate Level (CGL) 2026 notification in October 2026 with 17,000+ vacancies across central government ministries. Key posts: Income Tax Inspector, ASO (MEA, CVC), Sub Inspector (CBI), Tax Assistant. Tier I exam: Computer-based, 1 hour, 100 questions.",
    category: "National",
    examTags: ["SSC"],
    whyItMatters: "SSC CGL aspirants: The notification is expected in October 2026. Register on ssc.nic.in immediately. Note: any communication from SSC will come only from ssc.nic.in — beware of fake notifications.",
    sourceUrl: "https://ssc.gov.in/",
    sourceName: "SSC Official",
    youtubeQuery: "SSC CGL 2026 notification vacancies preparation strategy",
  },
  // ── High-Yield Additions (Maharashtra, National, Economy, Sci-Tech) ──
  {
    id: 31,
    slug: "ladki-bahin-yojana-maharashtra",
    date: "2026-08-05",
    title: "Mukhyamantri Majhi Ladki Bahin Yojana — ₹1,500/Month DBT to 2+ Crore Women",
    summary: "Maharashtra Government launched the Mukhyamantri Majhi Ladki Bahin Yojana providing ₹1,500 monthly direct financial assistance to eligible women aged 21-65 years whose family annual income is below ₹2.5 lakh. The scheme was allocated an annual budget outlay of ₹46,000 crore, making it Maharashtra's largest DBT welfare program.",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti"],
    whyItMatters: "Direct scheme questions in MPSC Rajya Seva, Combined & Talathi exams. Key facts: ₹1,500/month, age eligibility 21-65 years, annual family income cap ₹2.5 lakh, nodal dept: Women and Child Development.",
    sourceUrl: "https://maharashtra.gov.in/",
    sourceName: "Maharashtra Government Portal",
    youtubeQuery: "Majhi Ladki Bahin Yojana Maharashtra eligibility MPSC exam",
  },
  {
    id: 32,
    slug: "mumbai-metro-3-aqua-line",
    date: "2026-08-01",
    title: "Mumbai Metro Line 3 (Aqua Line) — First Underground Corridor Inaugurated",
    summary: "Prime Minister Narendra Modi inaugurated Phase 1 of Mumbai Metro Line 3 (Aqua Line) connecting Aarey JVLR to Bandra Kurla Complex (BKC). The 33.5 km corridor is Mumbai's first 100% underground metro line, constructed by MMRC with JICA loan assistance. It connects SEEPZ, international/domestic airports, BKC, and Cuffe Parade.",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti", "SSC"],
    whyItMatters: "Major infrastructure question for MPSC & BMC exams: Length (33.5 km), terminal stations (Aarey to Cuffe Parade), 27 stations (26 underground), JICA financial collaboration.",
    sourceUrl: "https://mmrcl.com/",
    sourceName: "Mumbai Metro Rail Corporation (MMRC)",
    youtubeQuery: "Mumbai Metro Line 3 Aqua line facts MPSC exam",
  },
  {
    id: 33,
    slug: "vadhavan-port-palghar-project",
    date: "2026-07-28",
    title: "Vadhavan Mega Port in Palghar — India's 13th Major Port Approved",
    summary: "The Union Cabinet approved the development of a mega deep-water container port at Vadhavan in Palghar district, Maharashtra, with a total investment of ₹76,220 crore. Jointly developed by JNPA and Maharashtra Maritime Board (MMB), it will rank among the top 10 container ports globally with a 20-metre natural draft able to dock mega vessels.",
    category: "Maharashtra",
    examTags: ["MPSC", "UPSC", "SSC"],
    whyItMatters: "UPSC GS-III & MPSC Geography/Economy: Location (Dahanu taluka, Palghar), equity ratio (JNPA 74% : MMB 26%), 13th major port under Major Port Authorities Act 2021, natural draft 20m.",
    sourceUrl: "https://pib.gov.in/",
    sourceName: "Press Information Bureau (PIB)",
    youtubeQuery: "Vadhavan Port Palghar Maharashtra UPSC MPSC economy",
  },
  {
    id: 34,
    slug: "marathi-classical-language-status",
    date: "2026-07-22",
    title: "Marathi Conferred 'Classical Language' (अभिजात भाषा) Status by Union Cabinet",
    summary: "The Union Cabinet chaired by PM Narendra Modi approved conferring 'Classical Language' (अभिजात भाषा) status to Marathi along with Pali, Prakrit, Assamese, and Bengali. This fulfilled a decades-long demand of 12 crore Marathi speakers based on Rangnath Pathare Committee report submitted to the Central Government.",
    category: "Maharashtra",
    examTags: ["MPSC", "UPSC", "Police Bharti"],
    whyItMatters: "Guaranteed question in MPSC Marathi language paper and General Studies. Criteria for classical language: High antiquity of early texts (1500-2000 years), ancient literature, distinct from modern forms. Rangnath Pathare Committee was the state committee.",
    sourceUrl: "https://pib.gov.in/",
    sourceName: "Ministry of Culture / PIB",
    youtubeQuery: "Marathi classical language status abhijat bhasha MPSC",
  },
  {
    id: 35,
    slug: "16th-finance-commission-arvind-panagariya",
    date: "2026-07-15",
    title: "16th Finance Commission — Constituted Under Dr. Arvind Panagariya",
    summary: "The Government of India constituted the 16th Finance Commission with Dr. Arvind Panagariya (former Vice-Chairman, NITI Aayog) as its Chairman. The Commission will make recommendations on tax devolution between Centre and States, grants-in-aid, and disaster management financing for the 5-year award period from 1 April 2026 to 31 March 2031.",
    category: "Economy",
    examTags: ["UPSC", "MPSC", "Banking", "IBPS"],
    whyItMatters: "Core Polity & Economy topic (Article 280 of Indian Constitution). Key facts: Chairman: Arvind Panagariya, 15th FC Chairman was NK Singh (recommended 41% vertical devolution). Report submission deadline and Terms of Reference.",
    sourceUrl: "https://fincomindia.nic.in/",
    sourceName: "Finance Commission of India",
    youtubeQuery: "16th Finance Commission Arvind Panagariya UPSC economy",
  },
  {
    id: 36,
    slug: "bharat-ratna-2024-five-awardees",
    date: "2026-07-10",
    title: "Bharat Ratna 2024 — Highest Civilian Honour Conferred to 5 Luminaries",
    summary: "President Droupadi Murmu conferred India's highest civilian award, Bharat Ratna, to five distinguished personalities: Karpoori Thakur (social justice champion, former Bihar CM), Lal Krishna Advani (former Deputy PM), P.V. Narasimha Rao (former PM, 1991 economic reforms), Chaudhary Charan Singh (former PM & farmers' leader), and Dr. M.S. Swaminathan (father of India's Green Revolution).",
    category: "National",
    examTags: ["MPSC", "UPSC", "SSC", "Police Bharti"],
    whyItMatters: "Awards & Honors is a staple section in all exams. Maximum 3 Bharat Ratnas were historically awarded in a single year; 2024 saw 5 recipients. Dr. M.S. Swaminathan (Green Revolution) and Karpoori Thakur are top question candidates.",
    sourceUrl: "https://pib.gov.in/",
    sourceName: "Rashtrapati Bhavan / PIB",
    youtubeQuery: "Bharat Ratna 2024 recipients UPSC SSC MPSC",
  },
  {
    id: 37,
    slug: "chief-justice-of-india-sanjiv-khanna",
    date: "2026-06-30",
    title: "Justice Sanjiv Khanna Appointed 51st Chief Justice of India (CJI)",
    summary: "Justice Sanjiv Khanna was sworn in as the 51st Chief Justice of India by President Droupadi Murmu, succeeding Justice D.Y. Chandrachud. Justice Khanna served on the Supreme Court since January 2019 and previously on the Delhi High Court. He is known for landmark judgments on EVM-VVPAT verification and Electoral Bonds transparency.",
    category: "National",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "Indian Judiciary & Constitutional bodies: Article 124(2), appointment convention of senior-most judge, oath administered under Article 124(6), retirement age of SC judges (65 years).",
    sourceUrl: "https://sci.gov.in/",
    sourceName: "Supreme Court of India",
    youtubeQuery: "Chief Justice of India 51st CJI Sanjiv Khanna UPSC polity",
  },
  {
    id: 38,
    slug: "unified-pension-scheme-ups-centre",
    date: "2026-06-25",
    title: "Unified Pension Scheme (UPS) Approved — Assured 50% Pension from April 2025",
    summary: "The Union Cabinet approved the Unified Pension Scheme (UPS) for central government employees, effective 1 April 2025. Key pillars: (1) Assured pension of 50% of average basic pay drawn over last 12 months before retirement for qualifying service of minimum 25 years. (2) Assured family pension of 60% of employee pension. (3) Minimum assured pension of ₹10,000/month after 10 years service. (4) Inflation indexation with Dearness Relief.",
    category: "Economy",
    examTags: ["UPSC", "MPSC", "Banking", "SSC"],
    whyItMatters: "Crucial difference between Old Pension Scheme (OPS), New Pension System (NPS), and Unified Pension Scheme (UPS). Government contribution increased from 14% to 18.5% under UPS. T.V. Somanathan Committee recommendations.",
    sourceUrl: "https://pib.gov.in/",
    sourceName: "Ministry of Finance / PIB",
    youtubeQuery: "Unified Pension Scheme UPS vs NPS vs OPS UPSC economy",
  },
  {
    id: 39,
    slug: "pm-surya-ghar-muft-bijli-yojana",
    date: "2026-06-18",
    title: "PM Surya Ghar: Muft Bijli Yojana — ₹75,021 Cr Rooftop Solar Initiative",
    summary: "Prime Minister launched the PM Surya Ghar: Muft Bijli Yojana aimed at installing rooftop solar panels in 1 crore households across India. The scheme provides up to 300 units of free electricity per month, reducing carbon emissions by 720 million tonnes of CO2 equivalent over 25 years. Subsidy: ₹30,000 for 1 kW, ₹60,000 for 2 kW, and ₹78,000 for 3 kW systems.",
    category: "Environment",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "Environment & Renewable Energy in GS-III: India's target of 500 GW non-fossil capacity by 2030, Panchamrit goals, MNRE implementation, and rooftop solar subsidy structure.",
    sourceUrl: "https://pmsuryaghar.gov.in/",
    sourceName: "Ministry of New and Renewable Energy",
    youtubeQuery: "PM Surya Ghar Muft Bijli Yojana solar subsidy UPSC",
  },
  {
    id: 40,
    slug: "paris-olympics-2024-india-swapnil-kusale",
    date: "2026-06-10",
    title: "Paris 2024 Olympics — Swapnil Kusale of Kolhapur Wins Historic Bronze",
    summary: "At the Paris 2024 Olympic Games, Maharashtra's Swapnil Kusale (from Kambalwadi, Kolhapur) won Bronze in Men's 50m Rifle 3 Positions, becoming the first Indian shooter to win an Olympic medal in this event. Manu Bhaker became the first Indian in post-independence history to win two medals at a single Olympics (10m Air Pistol individual & mixed team).",
    category: "Sports",
    examTags: ["MPSC", "Police Bharti", "SSC"],
    whyItMatters: "Extremely high probability question for MPSC and Police Bharti: Swapnil Kusale is an employee of Central Railway (Pune division) and hails from Kolhapur, Maharashtra. Manu Bhaker partner in mixed team: Sarabjot Singh.",
    sourceUrl: "https://olympics.com/",
    sourceName: "International Olympic Committee",
    youtubeQuery: "Swapnil Kusale bronze medal Paris Olympics MPSC sports",
  },
  {
    id: 41,
    slug: "samruddhi-mahamarg-nagpur-mumbai-complete",
    date: "2026-06-02",
    title: "Samruddhi Mahamarg (Mumbai-Nagpur Expressway) — 701 KM Fully Operational",
    summary: "The Hindu Hrudaysamrat Balasaheb Thackeray Maharashtra Samruddhi Mahamarg (Nagpur-Mumbai Super Communication Expressway) is a 701-km access-controlled expressway built at a cost of ₹55,000 crore by MSRDC. It connects 10 districts directly (Nagpur, Wardha, Amravati, Washim, Buldhana, Jalna, Chhatrapati Sambhajinagar, Ahmednagar, Nashik, Thane) and reduces travel time between Nagpur and Mumbai from 16 to 8 hours.",
    category: "Maharashtra",
    examTags: ["MPSC", "Police Bharti"],
    whyItMatters: "Essential MPSC Geography: Length 701 km, passes through 10 districts and 24 talukas, wildlife underpasses/overpasses (longest wildlife overpass in India), design speed 150 km/h.",
    sourceUrl: "https://mahammrda.maharashtra.gov.in/",
    sourceName: "MSRDC Maharashtra",
    youtubeQuery: "Samruddhi Mahamarg route districts facts MPSC exam",
  },
  {
    id: 42,
    slug: "ramsar-sites-maharashtra-nanur-thane-creek",
    date: "2026-05-25",
    title: "Maharashtra Wetlands & Ramsar Sites — Complete Ecological Guide",
    summary: "India's total Ramsar sites expanded to 85, with Maharashtra housing 3 internationally recognized Ramsar wetland sites: (1) Nandur Madhmeshwar in Nashik ('Bharatpur of Maharashtra'), (2) Lonar Lake in Buldhana (hyper-saline meteorite impact crater lake), and (3) Thane Creek Flamingo Sanctuary in Mumbai/Thane. Ramsar convention was adopted in Ramsar, Iran in 1971.",
    category: "Environment",
    examTags: ["MPSC", "UPSC", "Police Bharti"],
    whyItMatters: "MPSC Prelims & Forest Guard Bharti: Ramsar Convention date (2 Feb 1971 — World Wetlands Day), total Ramsar sites in India, 3 sites in Maharashtra, Lonar Lake mineral composition and haloarchaea pink water phenomenon.",
    sourceUrl: "https://moef.gov.in/",
    sourceName: "Ministry of Environment, Forest & Climate Change",
    youtubeQuery: "Ramsar sites in Maharashtra Lonar Thane creek MPSC environment",
  },
  {
    id: 43,
    slug: "nobel-peace-prize-2024-nihon-hidankyo",
    date: "2026-05-18",
    title: "Nobel Peace Prize 2024 — Awarded to Japan's Nihon Hidankyo",
    summary: "The Norwegian Nobel Committee awarded the 2024 Nobel Peace Prize to the Japanese grassroots organization Nihon Hidankyo (Confederation of A- and H-Bomb Sufferers Organizations). The award recognized their heroic witness testimonies to demonstrate that nuclear weapons must never be used again, maintaining the 'nuclear taboo' since Hiroshima and Nagasaki bombings in August 1945.",
    category: "International",
    examTags: ["UPSC", "MPSC", "Banking", "SSC"],
    whyItMatters: "UPSC International Relations & MPSC General Knowledge: Nobel Prize categories, Peace Prize presented in Oslo (Norway) whereas other Nobel prizes are awarded in Stockholm (Sweden). Hibakusha refers to atomic bomb survivors.",
    sourceUrl: "https://nobelprize.org/",
    sourceName: "The Nobel Foundation",
    youtubeQuery: "Nobel Peace Prize 2024 Nihon Hidankyo UPSC international",
  },
  {
    id: 44,
    slug: "brics-expansion-new-members-summit",
    date: "2026-05-10",
    title: "BRICS Summit & Expansion — New Members and Kazan Declaration",
    summary: "The 16th BRICS Summit held under Russia's presidency welcomed new full members: Egypt, Ethiopia, Iran, and the United Arab Emirates (UAE). Discussions focused on cross-border settlement in local currencies (BRICS Pay / New Development Bank), Global South representation, and reforming the UN Security Council and Bretton Woods institutions (IMF/World Bank).",
    category: "International",
    examTags: ["UPSC", "MPSC", "Banking"],
    whyItMatters: "UPSC GS-II & Banking awareness: Original BRIC coined by Jim O'Neill (2001), South Africa joined in 2010. New members admitted, New Development Bank (NDB) headquarters in Shanghai, Contingent Reserve Arrangement (CRA).",
    sourceUrl: "https://mea.gov.in/",
    sourceName: "Ministry of External Affairs (MEA)",
    youtubeQuery: "BRICS summit expansion new members UPSC international relations",
  },
  {
    id: 45,
    slug: "isro-gaganyaan-tv-d1-test-mission",
    date: "2026-05-02",
    title: "ISRO Gaganyaan Mission — Astronaut Designation and Flight Trials",
    summary: "ISRO announced the four designated astronaut-designates for India's premier human spaceflight mission Gaganyaan: Group Captain Prasanth Balakrishnan Nair, Group Captain Ajit Krishnan, Group Captain Angad Prathap, and Wing Commander Shubhanshu Shukla. The mission aims to launch a 3-member crew to a 400 km low Earth orbit for 3 days and return safely to Indian sea waters.",
    category: "Science & Tech",
    examTags: ["UPSC", "MPSC", "SSC"],
    whyItMatters: "UPSC Prelims & Mains GS-III: LVM3 launch vehicle (formerly GSLV Mk-III), CE-20 cryogenic engine human-rating, Crew Escape System (CES), Test Vehicle (TV-D1) pad abort tests, Vyommitra humanoid robot.",
    sourceUrl: "https://isro.gov.in/",
    sourceName: "Indian Space Research Organisation (ISRO)",
    youtubeQuery: "ISRO Gaganyaan mission astronauts facts UPSC science and tech",
  },
]

// Categories for filter UI
export const CA_CATEGORIES = [
  'All',
  'National',
  'International',
  'Economy',
  'Maharashtra',
  'Science & Tech',
  'Environment',
  'Sports',
]

// Exam tags for filter UI
export const CA_EXAM_TAGS = ['All', 'MPSC', 'UPSC', 'IBPS', 'Banking', 'SSC', 'Police Bharti']

// Get entry by slug
export function getCABySlug(slug) {
  return CURRENT_AFFAIRS.find(c => c.slug === slug) || null
}
